# Basic
title: Think Different
subtitle: 「Stay hungry. Stay foolish.」
welcome_message:  这里是我的技术博客，<a href="http://wwxiong.com">关于生活博客，也欢迎前往了解。</a>

description: 嗨，我是王雄 (@Outlier)，一名职业PHP开发，业余JavaScript开发者。现居北京，专注金融。我深信，所有的非常，都源于不懈的日常。
creator: <a href="http://wwxiong.com">@Outlier</a>

url: "http://wwxiong.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 项目, description: 我的项目, url: 'https://github.com/LensXiong/'}
    - {title: 关于, description: 其他博客, url: 'http://wwxiong.com/'}
    - {title: Vultr, description: 其他博客, url: 'http://www.vultr.com/?ref=6959672'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Outlier
    github: LensXiong
    twitter: Outlier
    gplus: 110287885508431241314
    mail: lensxiong@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-merlot