# Basic
title: Wangxiong's Tech
subtitle: 「Stay hungry. Stay foolish.」
description: 嗨，我是王雄 (@Outlier)，一名职业PHP开发者，业余JavaScript/Linux爱好者。现居北京，专注金融。我深信，所有的非常，都源于不懈的日常。
welcome_message: 这里是我的<a href="/#blog">Jekyll博客</a>，关于<a href="http://wwxiong.com/hexo_blog/">Hexo博客</a>，也欢迎<a href="http://wwxiong.com/hexo_blog/">前往了解</a>。
creator: <a href="http://wwxiong.com">@Outlier</a>

url: "http://wwxiong.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Jekyll
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Hexo, description: Hexo博客, url: 'http://wwxiong.com/hexo_blog/'}
    - {title: About, description: 相关信息, url: 'http://wwxiong.com/hexo_blog/about/'}
    - {title: Navbar, description: 我的导航, url: 'http://wwxiong.com/navigation/index.html'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 3
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: Outlier
    github: LensXiong
    twitter: AlanOutlier
    gplus: 110287885508431241314
    mail: lensxiong@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-merlot
